spring:
  profiles:
    active: dev

server:
  compression.enabled: true
  port: 8080

params:
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    maximumPoolSize: 10

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

---

spring:
  profiles: dev

  params:
    datasource:
      jdbcUrl: jdbc:derby:database/litecommerce;create=true # Embedded

---
