spring:
  jmx.enabled: false
  application:
    name: litecommerce

db:
  driver: org.h2.Driver
  password: ""
  username: ""
  url: jdbc:h2:./database/litecommerce;DB_CLOSE_ON_EXIT=FALSE

# hibernate:
#   dialect: org.hibernate.dialect.H2Dialect
#   show_sql: true
#   hbm2ddl.auto: create

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

server:
  compression.enabled: true
  port: 8080
