spring:
  jmx.enabled: false
  application:
    name: litecommerce

database:
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:./database/litecommerce;DB_CLOSE_ON_EXIT=FALSE
    username: ""
    password: ""
    maximumPoolSize: 5

# hibernate:
#   dialect: org.hibernate.dialect.H2Dialect
#   show_sql: true
#   hbm2ddl.auto: create

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

server:
  compression.enabled: true
  port: 8080
